version: '3.8'

services:
  mongo:
    image: mongo:5.0.10
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: '${DB_NAME}'
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
